[server]
maxUploadSize = 500
maxMessageSize = 500

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#E67E22"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#212529"
